# Generated by Django 5.2.18 on 2026-10-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='program',
            name='image_caption',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='program',
            name='image_path',
            field=models.CharField(blank=True, help_text='Path to an approved image within static assets, for example core/classroom.png.', max_length=200),
        ),
    ]
