# Generated by Django 5.2.18 on 2026-10-09 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clean_program_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, help_text='Approved public photograph. JPEG, PNG or WebP; up to 5 MB.', upload_to='programs/'),
        ),
        migrations.CreateModel(
            name='ProgramPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='programs/gallery/')),
                ('alt', models.CharField(max_length=200)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('order', models.PositiveIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.program')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
